apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-login-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-login
  template:
    metadata:
      labels:
        app: flask-login
    spec:
      serviceAccountName: flask-sa
      imagePullSecrets:
      - name: ecr-secret
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: flask-app
        image: 211125784755.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-config
        - secretRef:
            name: flask-secrets
        readinessProbe:
          httpGet:
            path: /login
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /login
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
      - name: sidecar-logger
        image: busybox
        command: ["sh", "-c", "tail -n+1 -F /var/log/flask/app.log"]
